version: "3.9"
services:
    postgres:
        env_file: .env
        image: postgres:12-alpine
        container_name: ${PROJECT_NAME}-postgres
        volumes:
            - "./sourcefiles/postgres:/var/lib/postgresql/data"
        ports:
            - "5433:5432"
        networks:
            testing_net:
                ipv4_address: 172.27.1.2

    php-fpm:
        build: sourcefiles/php-fpm
        working_dir: /application
        container_name: ${PROJECT_NAME}-php-fpm
        volumes:
            - ./application:/application
        depends_on:
            - postgres
        networks:
            testing_net:
                ipv4_address: 172.27.1.4

    webserver:
      build: sourcefiles/nginx
      container_name: ${PROJECT_NAME}-webserver
      volumes:
          - ./application:/application
          - ./sourcefiles/nginx/conf.d:/etc/nginx/conf.d
          - ./sourcefiles/nginx/log:/var/log/nginx/
      ports:
        - "9000:80"
      depends_on:
        - php-fpm
      networks:
            testing_net:
                ipv4_address: 172.27.1.3

networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.27.0.0/16