version: "3.1"
services:
    redis:
      image: redis:alpine
      container_name: ${PROJECT_NAME}-redis

    postgres:
      image: postgres:12
      container_name: ${PROJECT_NAME}-postgres
      volumes:
         - "./sourcefiles/postgres:/var/lib/postgresql/data"
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      ports:
       - "5432:5432"
      networks:
            testing_net:
                ipv4_address: 172.27.1.2
    php-fpm:
      build: sourcefiles/php-fpm
      container_name: ${PROJECT_NAME}-php-fpm
      working_dir: /application
      volumes:
        - ./application:/application
        - ./sourcefiles/php-fpm/www.conf:/etc/php/8.0/fpm/php-fpm.d/www.conf
        - ./sourcefiles/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini
      networks:
          testing_net:
              ipv4_address: 172.27.1.4
    webserver:
      build: sourcefiles/nginx
      container_name: ${PROJECT_NAME}-webserver
      working_dir: /application
      volumes:
          - ./application:/application
          - ./sourcefiles/nginx/conf.d:/etc/nginx/conf.d
      ports:
        - "9000:9000"
      networks:
            testing_net:
                ipv4_address: 172.27.1.3

networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.27.0.0/16